### ISSUE TITLE
have you seen archieml?

### ISSUE THREAD

**Issue by AlJohri** [techcoop/json-google-docs#5]
seems like a project with a similar philosophy. http://archieml.org/#google-docs

**Comment by colingagnon** [comment]
Hi AlJohri,

No, I hadn't seen it until you posted this issue, and yes, definitely a similar lib.  

I wanted this to be a very simple structure that will be readable as a regular document, without requiring a bunch of other markup.  Wasn't really intended to model complex JSON structures, but just a way to manage text blocks in my react apps. I did a more complicated case in the demo app to see if it would work for a "list of product".

Besides this, I guess the key difference is that this exposes a public URL that can be used without requiring a local build process or authentication.

But thanks for letting me know, it gave me some ideas to include (authentication and local compiling) for my webpack loader for this library (still under development) and I might give archieml a try for an upcoming project.

Cheers!
